### ISSUE TITLE
Fails to boot 1.18.2 PurPur

### ISSUE THREAD

**Issue by TomLewis** [eldoriarpg/SchematicBrushReborn#290]
Testing Schematic Brush Reborn locally before I push to prod, not sure when this broke, but I put the latest version of `Schematic Brush Reborn` on my test server, and it threw errors to do with `base_configuration.yml` so I stopped the server and rebooted seeing that the files had been created, then on a fresh configs this now shows:

```
[19:18:42] [Server thread/INFO]: [TAB] Enabled in 94ms
[19:18:42] [Server thread/INFO]: [SchematicBrushReborn] Enabling SchematicBrushReborn v2.5.0
[19:18:42] [Server thread/INFO]: [SchematicBrushReborn] Locale plugins\SchematicBrushReborn\messages\messages_en_US.properties is up to date.
[19:18:42] [Server thread/INFO]: [SchematicBrushReborn] Registered entry of type storage with de.eldoria.schematicbrush.schematics.SchematicBrushCache at Schematic Registry
[19:18:42] [Server thread/ERROR]: [SchematicBrushReborn] Plugin failed to enable.
java.lang.NullPointerException: Cannot invoke "de.eldoria.schematicbrush.config.Configuration.schematicConfig()" because "this.configuration" is null
	at de.eldoria.schematicbrush.schematics.SchematicBrushCache.reload(SchematicBrushCache.java:70) ~[schematicbrushreborn-core-2.5.0.jar:?]
	at de.eldoria.schematicbrush.schematics.SchematicBrushCache.init(SchematicBrushCache.java:55) ~[schematicbrushreborn-core-2.5.0.jar:?]
	at de.eldoria.schematicbrush.schematics.SchematicRegistryImpl.register(SchematicRegistryImpl.java:22) ~[schematicbrushreborn-core-2.5.0.jar:?]
	at de.eldoria.schematicbrush.SchematicBrushRebornImpl.onPluginEnable(SchematicBrushRebornImpl.java:141) ~[schematicbrushreborn-core-2.5.0.jar:?]
	at de.eldoria.schematicbrush.libs.eldoutilities.plugin.EldoPlugin.onEnable(EldoPlugin.java:252) ~[schematicbrushreborn-core-2.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by rainbowdashlabs** [comment]
Can you try 2.5.2. It should be fixed there.  I uploaded it on spigot.

**Comment by rainbowdashlabs** [comment]
Ah yes. Thats a problem with the older versions of spigot/paper. Although declaring it in the library loader I can override libraries already present in paper with it. In that case snake yaml. Thats why I provide legacy builds which shade stuff like a newer snake yaml version on my discord. Sadly spigot only allows me to publish one jar and the shaded jar is too large for spigot. So if you want you can come on my discord and download it there after registering your license code, which I send you on spigot.
